package com.prestamos.dto;
// Generated 17/07/2014 03:01:05 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * TipoUsuario generated by hbm2java
 */
public class TipoUsuario  implements java.io.Serializable {


     private int codigo;
     private String tipo;
     private Set usuarios = new HashSet(0);

    public TipoUsuario() {
    }

	
    public TipoUsuario(String tipo) {
        this.tipo = tipo;
    }
    public TipoUsuario(String tipo, Set usuarios) {
       this.tipo = tipo;
       this.usuarios = usuarios;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


